#!/usr/bin/env python

"""
Autogenerated by CHEETAH: The Python-Powered Template Engine
 CHEETAH VERSION: 0.9.15
 Generation time: Fri Jul 16 18:39:55 2004
   Source file: prewikka/modules/main/templates/MessageDetails.tmpl
   Source file last modified: Fri Jul 16 10:31:37 2004
"""

__CHEETAH_genTime__ = 'Fri Jul 16 18:39:55 2004'
__CHEETAH_src__ = 'prewikka/modules/main/templates/MessageDetails.tmpl'
__CHEETAH_version__ = '0.9.15'

##################################################
## DEPENDENCIES

import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from prewikka.Views import NormalLayoutView

##################################################
## MODULE CONSTANTS

try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFS=valueFromSearchList
VFN=valueForName
currentTime=time.time

##################################################
## CLASSES

class MessageDetails(NormalLayoutView):
    """
    
    Autogenerated by CHEETAH: The Python-Powered Template Engine
    """

    ##################################################
    ## GENERATED METHODS


    def __init__(self, *args, **KWs):
        """
        
        """

        NormalLayoutView.__init__(self, *args, **KWs)

    def display_node(self,
            node,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        Generated from #def display_node($node) at line 5, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        display = ("block", "none")[VFN(node,"hidden",True)]
        write('<div class="message_details">\n\t<div class="message_details_title"><a href="javascript:toggleVisibility(\'section_')
        write(filter(VFN(node,"id",True), rawExpr='$node.id')) # from line 8, col 83.
        write('\')">')
        write(filter(VFN(node,"name",True), rawExpr='$node.name')) # from line 8, col 95.
        write('</a></div>\n\t<div class="message_details_content" id="section_')
        write(filter(VFN(node,"id",True), rawExpr='$node.id')) # from line 9, col 51.
        write('" style="display: ')
        write(filter(display, rawExpr='$display')) # from line 9, col 77.
        write('">\n')
        for entry in VFN(node,"entries",True):
            write('')
            if isinstance(VFN(entry,"value",True), dict):
                write('\t\t\t\t')
                write(filter(VFS(SL + [globals(), __builtin__],"display_node",False)(VFN(entry,"value",True)), rawExpr='$display_node($entry.value)')) # from line 12, col 5.
                write('\n')
            else:
                write('\t\t\t\t<div class="message_details_entry">\n\t\t\t\t\t<div class="message_details_entry_name">')
                write(filter(VFN(entry,"name",True), rawExpr='$entry.name')) # from line 15, col 46.
                write('</div>\n\t\t\t\t\t<div class="message_details_entry_value">')
                write(filter(VFN(entry,"value",True), rawExpr='$entry.value')) # from line 16, col 47.
                write('</div>\n\t\t\t\t</div>\n')
            write('')
        write('\t</div>\n</div>\n')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def main_content(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        Generated from #block main_content at line 4, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('\n')
        write(filter(VFS(SL + [globals(), __builtin__],"display_node",False)(VFS(SL + [globals(), __builtin__],"node",True)), rawExpr='$display_node($node)')) # from line 24, col 1.
        write('\n\n')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def writeBody(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        This is the main method generated by Cheetah
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('\n')
        self.main_content(trans=trans) # generated from ('main_content', '#block main_content') at line 4, col 1.
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        
    ##################################################
    ## GENERATED ATTRIBUTES


    _mainCheetahMethod_for_MessageDetails= 'writeBody'


# CHEETAH was developed by Tavis Rudd, Mike Orr, Ian Bicking and Chuck Esterbrook;
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org

##################################################
## if run from command line:
if __name__ == '__main__':
    MessageDetails().runAsMainProgram()

