#!/usr/bin/env python

"""
Autogenerated by CHEETAH: The Python-Powered Template Engine
 CHEETAH VERSION: 0.9.15
 Generation time: Fri Jul 16 18:49:31 2004
   Source file: prewikka/modules/main/templates/MessageListing.tmpl
   Source file last modified: Fri Jul 16 18:49:04 2004
"""

__CHEETAH_genTime__ = 'Fri Jul 16 18:49:31 2004'
__CHEETAH_src__ = 'prewikka/modules/main/templates/MessageListing.tmpl'
__CHEETAH_version__ = '0.9.15'

##################################################
## DEPENDENCIES

import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from prewikka.Views import NormalLayoutView

##################################################
## MODULE CONSTANTS

try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFS=valueFromSearchList
VFN=valueForName
currentTime=time.time

##################################################
## CLASSES

class MessageListing(NormalLayoutView):
    """
    
    Autogenerated by CHEETAH: The Python-Powered Template Engine
    """

    ##################################################
    ## GENERATED METHODS


    def __init__(self, *args, **KWs):
        """
        
        """

        NormalLayoutView.__init__(self, *args, **KWs)

    def message_listing_header(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        Generated from #def message_listing_header at line 5, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def del_filter(self,
            name,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        Generated from #def del_filter(name) at line 70, col 2.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('')
        if VFS(SL + [globals(), __builtin__],"active_filter",True) == name:
            write("\t\t\t<a href='")
            write(filter(VFS(SL + [globals(), __builtin__],"remove_active_filter",True), rawExpr='$remove_active_filter')) # from line 72, col 13.
            write("'>del filter</a>\n")
        write('')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def main_content(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        Generated from #block main_content at line 4, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write(filter(VFS(SL + [globals(), __builtin__],"message_listing_header",True), rawExpr='$message_listing_header')) # from line 7, col 1.
        write('''
<div id="message_list_edition">
	<div id="timeline">
	<form action="?" method="post">
''')
        for name, value in VFS(SL + [globals(), __builtin__],"timeline.form_hiddens",True):
            write('\t\t\t<input type="hidden" name="')
            write(filter(name, rawExpr='$name')) # from line 12, col 31.
            write('" value="')
            write(filter(value, rawExpr='$value')) # from line 12, col 45.
            write('"/>\n')
        write('\t\t<div id="timeline_label">Step:</div>\n\t\t<div id="timeline_value">\n\t\t\t<input name="timeline_value" type="text" size="8" value="')
        write(filter(VFS(SL + [globals(), __builtin__],"timeline.value",True), rawExpr='$timeline.value')) # from line 16, col 61.
        write('''"/>
		</div>
			<div id="timeline_unit">
				<select name="timeline_unit">
					<option value="sec" ''')
        write(filter(VFS(SL + [globals(), __builtin__],"timeline.sec_selected",True), rawExpr='$timeline.sec_selected')) # from line 20, col 26.
        write('>Seconds\n\t\t\t\t\t<option value="min" ')
        write(filter(VFS(SL + [globals(), __builtin__],"timeline.min_selected",True), rawExpr='$timeline.min_selected')) # from line 21, col 26.
        write('>Minutes\n\t\t\t\t\t<option value="hour" ')
        write(filter(VFS(SL + [globals(), __builtin__],"timeline.hour_selected",True), rawExpr='$timeline.hour_selected')) # from line 22, col 27.
        write('>Hours\n\t\t\t\t\t<option value="day" ')
        write(filter(VFS(SL + [globals(), __builtin__],"timeline.day_selected",True), rawExpr='$timeline.day_selected')) # from line 23, col 26.
        write('>Days\n\t\t\t\t\t<option value="month" ')
        write(filter(VFS(SL + [globals(), __builtin__],"timeline.month_selected",True), rawExpr='$timeline.month_selected')) # from line 24, col 28.
        write('>Months\n\t\t\t\t\t<option value="year" ')
        write(filter(VFS(SL + [globals(), __builtin__],"timeline.year_selected",True), rawExpr='$timeline.year_selected')) # from line 25, col 27.
        write('''>Years
				</select>
			</div>
			<div id="timeline_submit">
				<input type="submit"  value="apply">
			</div>
	</form>
	</div>
	<div id="timeline_range">
		<div id="timeline_start">From ''')
        write(filter(VFS(SL + [globals(), __builtin__],"timeline.start",True), rawExpr='$timeline.start')) # from line 34, col 33.
        write('</div>\n\t\t<div id="timeline_end">To ')
        write(filter(VFS(SL + [globals(), __builtin__],"timeline.end",True), rawExpr='$timeline.end')) # from line 35, col 29.
        write('''</div>
	</div>
	<div id="timeline_navigation">
		<div id="timeline_prev"><a href="''')
        write(filter(VFS(SL + [globals(), __builtin__],"timeline.prev",True), rawExpr='$timeline.prev')) # from line 38, col 36.
        write('">prev</a></div>\n\t\t<div id="timeline_current"><a href="')
        write(filter(VFS(SL + [globals(), __builtin__],"timeline.current",True), rawExpr='$timeline.current')) # from line 39, col 39.
        write('">current</a></div>\n\t\t<div id="timeline_next"><a href="')
        write(filter(VFS(SL + [globals(), __builtin__],"timeline.next",True), rawExpr='$timeline.next')) # from line 40, col 36.
        write('''">next</a></div>
	</div>
</div>

<div id="message_list_result">
<form action="?" method="post">
''')
        for name, value in VFS(SL + [globals(), __builtin__],"delete_form_hiddens",True):
            write('\t<input type="hidden" name="{NAME}" value="{VALUE}"/>\n')
        write('''<table>
	<thead>
		<tr>
			''')
        write(filter(VFS(SL + [globals(), __builtin__],"message_fields_header",True), rawExpr='$message_fields_header')) # from line 52, col 4.
        write('''
		</tr>
	</thead>
	<tbody>
''')
        row_classes = ("table_row_even", "table_row_odd")
        write('')
        cnt = 0
        write('')
        for message in VFS(SL + [globals(), __builtin__],"messages",True):
            write('')
            globalSetVars["message"] = message
            write("\t\t\t<tr class='")
            write(filter(row_classes[cnt%2], rawExpr='$row_classes[$cnt%2]')) # from line 60, col 15.
            write("'>\n\t\t\t\t")
            write(filter(VFS(SL + [globals(), __builtin__],"message_fields",True), rawExpr='$message_fields')) # from line 61, col 5.
            write("\n\t\t\t\t<td class='static_content_column'><a href='")
            write(filter(VFN(message,"summary",True), rawExpr='$message.summary')) # from line 62, col 48.
            write("'>summary</a></td>\n\t\t\t\t<td class='static_content_column'><a href='")
            write(filter(VFN(message,"details",True), rawExpr='$message.details')) # from line 63, col 48.
            write("'>details</a></td>\n\t\t\t\t<td class='static_content_column'><input type='checkbox' name='idents' value='")
            write(filter(VFN(message,"analyzerid",True), rawExpr='$message.analyzerid')) # from line 64, col 83.
            write(':')
            write(filter(VFN(message,"ident",True), rawExpr='$message.ident')) # from line 64, col 103.
            write("'/></td>\n\t\t\t</tr>\n")
            cnt += 1
            write('')
        write('\t</tbody>\n\t<tfoot>\n\t<td>')
        write(filter(VFS(SL + [globals(), __builtin__],"del_filter",False)("alert.classification.name"), rawExpr='$del_filter("alert.classification.name")')) # from line 75, col 6.
        write('</td>\n\t<td>')
        write(filter(VFS(SL + [globals(), __builtin__],"del_filter",False)("alert.source.node.address.address"), rawExpr='$del_filter("alert.source.node.address.address")')) # from line 76, col 6.
        write('</td>\n\t<td>')
        write(filter(VFS(SL + [globals(), __builtin__],"del_filter",False)("alert.target.node.address.address"), rawExpr='$del_filter("alert.target.node.address.address")')) # from line 77, col 6.
        write('</td>\n\t<td>')
        write(filter(VFS(SL + [globals(), __builtin__],"del_filter",False)("alert.analyzer.model"), rawExpr='$del_filter("alert.analyzer.model")')) # from line 78, col 6.
        write('''</td>
	<td></td>
	<td></td>
	<td></td>
	<td class='static_content_column'><input type='submit' value='delete'/></td>
	</tfoot>
</table>
</form>
</div>
''')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def writeBody(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        This is the main method generated by Cheetah
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('\n')
        self.main_content(trans=trans) # generated from ('main_content', '#block main_content') at line 4, col 1.
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        
    ##################################################
    ## GENERATED ATTRIBUTES


    _mainCheetahMethod_for_MessageListing= 'writeBody'


# CHEETAH was developed by Tavis Rudd, Mike Orr, Ian Bicking and Chuck Esterbrook;
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org

##################################################
## if run from command line:
if __name__ == '__main__':
    MessageListing().runAsMainProgram()

